spring.datasource.url=jdbc:postgresql://localhost:5433/webstore_db
spring.datasource.username=postgres
spring.datasource.password=xmarcelox
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=QXJtY2Vsb1dlYnN0b3JlSnd0U2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Ng==
jwt.expirationMs=3600000

